const quotes = [
{highlight : "Half the time I don't know the restaurants instagram handle.	",
quote : "They usually tag the restaurant's location in an Instagram Story because 'half the time I don't know their handle.'	",
source : "2.35"},
{highlight : "They had a bad experience with a restaurants that kept sending emails.	",
quote : "They had a bad experience with a restaurants because they kept sending email and was hard to unsubscribe from.	",
source : "12.23"},
{highlight : "They received a badge from a restaurant for being a top fan.	",
quote : "They received a badge from a restaurant for being a top fan because 'I like and comment, and tag my friends asking them to check it out when they are there'	",
source : "10.53"},
{highlight : "It was great and expensive but not that expensive as tasting menus go.	",
quote : "",
source : "6.15"},
{highlight : "They only pay attention to emails they are expecting.	",
quote : "They don't think they get emails from restaurants 'I might be getting emails? but I have NO idea' They only pay attention to emails they are 'looking out for or expecting...I get a lot of promos but I don't really pay attention to them'	",
source : "5.41"},
{highlight : "They follow a small restaurant because 'I was inclined to help them out.'	",
quote : "Despite not following many places they follow a small restaurant that is 'freakingly amazing and has very good food' because 'they told me to and the experience was so amazing. I was inclined to help them out.'	",
source : "4.31"},
{highlight : "They were frustrated with the customer service because no one took responsibility.	",
quote : "They were frustrated with Postmates' customer service because at first 'they had no phone number to reach them,' and then when they did call 'I had to talk to several people over a long time and everybody I talked to had a different story.' No one took responsibility for their issue.	",
source : "3.36"},
{highlight : "Each little cow piece cost $200!	",
quote : "It was a really nice experience and the service was outstanding from the get-go even though it was 'it was ridiculously expensive, each little cow piece cost $200!'	",
source : "8.24"},
{highlight : "They find emails annoying.	",
quote : "They find emails annoying and don't read most of them because 'it is too much clutter, junk and clogs my inbox'	",
source : "3.43"},
{highlight : "They only get promo notifications because they forget to turn them off.	",
quote : "",
source : "12.31"},
{highlight : "I want restaurants to know that I am tagging about them.	",
quote : "Sometimes if they follow a restaurant they will mention them in their story because 'I want them to know that I am tagging about them.	",
source : "2.36"},
{highlight : "They write reviews to help the restaurant improve.	",
quote : "They rate or write a review every time they order delivery from a restaurant to help the restaurant improve.	",
source : "1.19"},
{highlight : "They write reviews because they want other guests to have that information.	",
quote : "They rate or write a review every time they order delivery from a restaurant because ratings are a 'major factor' in their decision, and they want other guests to have that information.	",
source : "1.18"},
{highlight : "They are a review wizard and discount 5-star and 1-star reviews.	",
quote : "They are a review wizard and discount 5-star and 1-star reviews because '5's and 1's are not nearly as interesting as 4's and 3's and if I am still on the fence, i'll go to 2's'	",
source : "8.42"},
{highlight : "When Postmates didn't fix a mistake, they told everybody about it.	",
quote : "While they don't usually write reviews, they were so frustrated when Postmates' customer service didn't fix a mistake, 'I went to the Better Business Bureau, posted on Facebook, I contacted their customer service [...] and will tell everybody who wants to hear about it because I was so frustrated about Postmates.'	",
source : "3.37"},
{highlight : "When they find 'the best' version of a local dish they put it on TripAdvisor.'	",
quote : "When they find 'the best' version of a local dish, 'I have my own opinion and I put it on TripAdvisor.' They explain why they think it's the best and try to put it in a 'format other people will think is interesting.'	",
source : "9.12"},
{highlight : "The world is not going to fall apart not knowing what is about to go into my mouth.	",
quote : "No, I am not posting pictures of my food because 'the world is not going to fall apart not knowing what is about to go into my mouth'	",
source : "8.52"},
{highlight : "They 'of course' post it on their Instagram story.	",
quote : "They 'of course' post it on their Instagram story 'if I am at a restaurant that has delicious food.'	",
source : "2.33"},
{highlight : "They gave the $50 giftcard to their friends because 'I was not going to go back'	",
quote : "They gave the $50 giftcard they received as a compensation for the bad experience to their friends because 'I was not going to go back'	",
source : "10.28"},
{highlight : "They read reviews but 'I'm not very good about giving feedback myself.'	",
quote : "",
source : "2.32"},
{highlight : "They only write reviews if they have an exceptionally great or bad experience.	",
quote : "They have a Yelp account but do not usually write reviews 'unless I have an exceptionally great experience or bad experience...but I have the app and that makes it easier to browse'	",
source : "5.17"},
{highlight : "They are 'very picky' about what they post on social media.	",
quote : "They are 'very picky' about what they post on social media because 'I don't wanna be one of those people who participate in the fads and whatnot.'	",
source : "4.3"},
{highlight : "The problem was resolved, they wrote a good review, but they won't order again.	",
quote : "They recently ordered delivery from a new restaurant, and the food was burnt. The problem was resolved and they wrote a good review, but they won't order again from there because they 'can't trust the quality of the food.'	",
source : "1.15"},
{highlight : "They usually check in on facebook because they like to spread the word.	",
quote : "They usually check in on facebook and talk with their friends in the neighborhood because they like to spread the word about a good restaurant 'I always ask if they have tried Legno, It's really good, we should really go there, let's set up a date to go eat.'	",
source : "3.41"},
{highlight : "They 'definitely' don't want to sign up to communicate with restaurants over text.	",
quote : "They 'definitely' don't want to sign up to communicate with restaurants over text because 'it would annoy me.'	",
source : "3.44"},
{highlight : "These days they only take pictures if it's 'a knock-out plate or if I'm traveling.	",
quote : "They used to take more pictures of their food but these days they only take pictures of their drinks or because it is 'a really knock-out plate or if I'm traveling and it is a specialty dish, like something eccentric, not burger and fries.'	",
source : "3.42"},
{highlight : "They make it a point to highlight good services to the manager.	",
quote : "They make it a point to highlight good services to the manager because 'that is a very thankless job and I think, that makes the biggest impact everywhere we go'	",
source : "8.17"},
{highlight : "I'm not a picture taker of my food and never really have been.	",
quote : "",
source : "6.2"},
{highlight : "I want others to know about a bad experience or else I am doing a disservice to them.	",
quote : "I certainly did write a review on yelp because 'if I had a bad experience then I want other people to know or else I am doing a disservice to them'	",
source : "10.29"},
{highlight : "If that would have been my first experience at Olive Garden I would have not gone back.	",
quote : "",
source : "4.15"},
{highlight : "They wait to review to be sure the service and food are consistent.	",
quote : "They wait to review the restaurant 'till they know the restaurant and the people at the restaurant' and be sure the service and food is consistent.	",
source : "8.45"},
{highlight : "They do review restaurants but they don't tend to leave it on the first visit.	",
quote : "They do review restaurants but they don't tend to leave it on the first visit because 'you're on vacation and you suppose to be relaxed but instead you spent the whole day on your feet and now you are crancky when you got to the restaurant because you didnt get what you wanted'	",
source : "8.44"},
{highlight : "They didn't feel that UberEats was transparent about how the order of delivery happens.	",
quote : "",
source : "12.56"},
{highlight : "The newsletters 'come in infrequently so I forget to unsubscribe.'	",
quote : "I haven't unsubscribed from Cava and Sweet Greens newsletters because 'they come in infrequently so I forget to unsubscribe.'	",
source : "2.26"},
{highlight : "They were still hungry but didn't want to order more expensive food.	",
quote : "They were frustrated with the small portions, still hungry but didn't want to order more food because it was expensive and they 'weren't able to talk to anyone.'	",
source : "5.23"},
{highlight : "The emails were surprising 'I don't understand how they got my information.'	",
quote : "They were surprised about some emails from Cava and Sweet Greens from some random cities because 'I don't understand how they got my information.'	",
source : "2.27"},
{highlight : "Food pictures in Instagram Stories are less obnoxious than in the feed.	",
quote : "They prefer to post food pictures into their Instagram Story and not their feed because 'I can still put it out there but it's hopefully less obnoxious.'	",
source : "2.34"},
{highlight : "The local coffee shop is part of their identity.	",
quote : "They are a brand ambassador for a local coffee shop (Barnies) to encourage others to visit too because it’s part of their identity and wants to extend that to others.	",
source : "7.18"},
{highlight : "The pizza is so bad that they will get their food from another spot like Chipotle.	",
quote : "",
source : "12.25"},
{highlight : "I don't consider myself a foodie because I don't have a food blog.	",
quote : "I don't consider myself a foodie because 'I don't have a food blog, I don't do #foodporn on Instagram.' If they like something they talk about it and that's it.	",
source : "11.7"},
{highlight : "They leave reviews if management didn't do anything to alleviate a bad experience.	",
quote : "",
source : "5.2"},
{highlight : "Recently they wrote an exceptional review online because customer service made up for a bad experience.	",
quote : "",
source : "13.9"},
{highlight : "Despite not so great food experiences they would go back for the great service.	",
quote : "Despite two not so great food experiences they 'think they would go back to the restaurant, even though they've made the plates smaller, the service is really great and some of the best that I've ever experiences and I would go back for that.'	",
source : "5.27"},
{highlight : "They drive over an hour because the restaurant goes above and beyond.	",
quote : "They drive 1hr 20 minutes to a restaurant because 'they go above and beyond. As soon as we walk in the door, they start getting foil and wrapping up all the rib bones' for our dog.	",
source : "8.2"},
{highlight : "They consider Smoothie King 'very kind' because of their quick app support.	",
quote : "They consider Smoothie King 'very kind' because recently after a promotion didn't show up in her app 'I contacted app support and they changed it immediately after I showed proof of payment.'	",
source : "4.29"},
{highlight : "Perks for downloading the app would entice them to download it.	",
quote : "They would usually order online through the computer site and then see perks for downloading the app that would entice them download it.	",
source : "12.3"},
{highlight : "Being a regular, 'that's what Cheers is: where they know you by name.'	",
quote : "",
source : "11.3"},
{highlight : "They were 'very pissed off' because they overpromised a refund.	",
quote : "They were 'very pissed off' because Postmates made a mistake, promised a refund and a credit, but then 'had the audacity' to charged their card for the credit. They overpromised 'and instead still have not, do this day, refunded my money.'	",
source : "3.35"},
{highlight : "Pay at the table with the kiosk was ok because 'I wanted to get out quickly'.	",
quote : "They didn't mind being able to the pay at the table with the kiosk because 'I wanted to get out of the Red Robin as quickly as possible, the service was so poor.'	",
source : "3.32"},
{highlight : "The fish quality was poor and management didn't do anything.	",
quote : "Their least favorite restaurant experience was at a Mexican restaurant close to their last apartment where the fish quality was poor and management didn't do anything.	",
source : "5.39"},
{highlight : "Sometimes they glance at a restaurant's emails because they want to 'see what's new.	",
quote : "Sometimes they glance at a restaurant's emails because they want to 'see what's new but I wouldn't rush out to be there.'	",
source : "2.28"},
{highlight : "They are Indian and 'feel a connection to home when they eat there.	",
quote : "They're a regular at a nearby Indian restaurant because they are Indian and 'feel a connection to 'home'' when they eat there.	",
source : "1.16"},
{highlight : "Routines minimize the decision-making and create relationships.	",
quote : "Their family thrives on routine, including ordering Indian once a week from their go-to place nearby and going out to their favorite Italian restaurant on the weekends, because it minimizes the decision-making and creates ongoing relationships.	",
source : "7.5"},
{highlight : "I like to pay for my services at the time I receive them.	",
quote : "They don't like to pay in advance in an app because 'I like to pay for my services at the time I receive them'	",
source : "3.49"},
{highlight : "Seeing familiar faces and feeling welcomed is just as important as the food.	",
quote : "Seeing familiar faces and feeling welcomed is just as important as the food because it heightens their time together as a family.	",
source : "7.12"},
{highlight : "They frequent this restaurant because 'the owners take the time to know their customers'.	",
quote : "",
source : "10.17"},
{highlight : "They have a summer Tuesday night dinner ritual.	",
quote : "They have a summer Tuesday night dinner ritual because they go to the movies with their son and then go to a restaurant near the movies. They take turns with their partner. Mon, Weds and Thurs, they cook.	",
source : "11.19"},
{highlight : "They want to receive emails offering free meals and champagne.	",
quote : "They would want to receive emails from restaurants that has photos and videos of their favorite cheese meting over and saying 'thank you for being a loyal customer, happy bday and come in for a free meal for two or come in for a meal and have a free glass of champagne'	",
source : "10.54"},
{highlight : "Servers checking on them 'gives me a friendly, warm feel.'	",
quote : "They want servers to check on them periodically and not just flag them down for the check because 'that gives me a friendly, warm feel.'	",
source : "3.21"},
{highlight : "The coffee shop provides comfort, a relaxing part of the routine.	",
quote : "Barneys is now engrained in their routine because it fits perfectly in their stressful schedule providing a comfort, relaxing part of routine.	",
source : "7.25"},
{highlight : "The manager had comped the entire meal and they might go back because of it.	",
quote : "When the bill came the manager had comped the entire meal, so despite the small servings sizes, they had 'one of the best experiences...because of the service'. They weren't sure if they were going to go back to this restaurant after this experience, 'but we might because of the exceptional service.'	",
source : "5.25"},
{highlight : "The screen at the table makes servers believe they did enough to get 20% tip.	",
quote : "They don't like the screen at the table because 'in the server's mind they have done what they need to do to get 20% tip and they absolutely have not'	",
source : "8.61"},
{highlight : "They believe that their OpenTable preferences will be honored in a good restaurant.	",
quote : "",
source : "11.39"},
{highlight : "They went back to the restaurant because they were super attentive.	",
quote : "",
source : "12.14"},
{highlight : "The email about the summer menu updates that caught their eye.	",
quote : "",
source : "6.29"},
{highlight : "They revisited a restaurant to make sure 'it was still as good as I remembered.' before suggesting it to friends.	",
quote : "",
source : "2.7"},
{highlight : "They signed up for emails to get good deals and points for free stuff.	",
quote : "They signed up for emails from a few chains because they hope to get good deals and 'to get points to get free stuff.	",
source : "4.22"},
{highlight : "We don't really like trying new things.	",
quote : "They identify as creatures of habit because 'We don't really like trying new things.'	",
source : "4.1"},
{highlight : "It goes from 'you are serving me' to 'we know each other'.	",
quote : "They invest and value a 2-way relationship because 'I don't call up and say this is so and so and I expect this treatment' 'It goes from you are serving me to we know each other'	",
source : "8.22"},
{highlight : "There is something about getting the bill and reviewing everything.	",
quote : "They don't like to be auto charged because 'there is something about getting the bill and reviewing everything.'	",
source : "3.5"},
{highlight : "They'd been there for drinks so they went back for food.	",
quote : "They knew what they were getting into because they'd been there for drinks so they went back for food.	",
source : "6.3"},
{highlight : "They would be excited about 'some sort of discount for coming in.'	",
quote : "They would be excited about an email if they got something to eat at the restaurant, 'some sort of discount for coming in.'	",
source : "2.46"},
{highlight : "They cant stand wait staff constantly interrupting conversations.	",
quote : "They appreciate details like the wait staff and support staff ratio because they 'cant stand wait staff constantly picking stuff off my table. It stops conversation instead they should out of your hair and let you enjoy the people you are actually there with'	",
source : "8.26"},
{highlight : "Instead of putting the steak back on the grill they microwaved it.	",
quote : "They sent the steak back because 'it was so undercooked that it has blood and it was purple in the inside and instead of putting it back on the grille they microwaved it and brought it back to me'	",
source : "10.27"},
{highlight : "My daughter’s Mac and Cheese was cold and they were not very attentive.	",
quote : "Recently they got annoyed in a Red Robin because 'My daughter’s Mac and Cheese was cold and they were not very attentive.'	",
source : "3.3"},
{highlight : "They have a rule that they never cook on Sundays.	",
quote : "On the weekends sometimes they cook at home except for Sunday because their partner has a rule that they never cook on Sundays 'unless we have visitors or are eating leftovers from Saturday' so they like to try new restaurants or go back to ones they love.	",
source : "11.3"},
{highlight : "They use Uber Eats over Postmates for promotions and the rewards program.	",
quote : "Postmates has a lot of option foodwise but I use Uber Eats because ' it is convenient and they use Paypal and Postmates have less promotions and no rewards program yet'	",
source : "10.12"},
{highlight : "Nashville is a tremendous food experience.	",
quote : "They absolutely love Nashville 'it is one of my favorite city to experience' because 'it is a tremendous food experience'	",
source : "8.5"},
{highlight : "The McDonald’s app pops up a deal if you are near a location.	",
quote : "They like the McDonald’s app because if you are near a location 'it will pop up a deal or send you a coupon and my daughter eats it.'	",
source : "3.46"},
{highlight : "They don't want emails unless there are discounts or deals.	",
quote : "",
source : "5.44"},
{highlight : "They invest in the humans, chat with the servers and that makes a difference.	",
quote : "They have a very different (dining) experience because they 'invest in the humans, chat with the servers about the kids and school, and that makes a difference to the people who are working'	",
source : "8.21"},
{highlight : "They thought it was fun to hang out with the staff after closing hours. 	",
quote : "They thought it was fun to get drunk, spend a lot of money on food on a weeknight, hang out after closing hours with the staff.	",
source : "6.18"},
{highlight : "The servers know me by name and are eager to have me sit in their section.	",
quote : "They feel welcomed in the restaurant because ' the servers know me by name and are eager to have me sit in their section – I don't cause problems and I tip really well'	",
source : "8.18"},
{highlight : "It was memorable because of how fun it was to watch their partners reaction.	",
quote : "They shared a special experience with their partner and it was memorable because of how fun it was to watch their reaction.	",
source : "6.41"},
{highlight : "I pretty much know everything on the menu so I don't have to think too much.	",
quote : "I'm a regular because I'm recognized, somettimes I get free stuff, I pretty much know everything on the menu so I don't have to think too much, and I literally have to walk by it every day so I see it every day.	",
source : "6.12"},
{highlight : "They were happy that while the food wasn't great, the service was.	",
quote : "Recently in a restaurant, they had to send food back to the kitchen but despite that disappointment were happy at the end because 'while the food wasn't great, the service was. They took a percentage off the bill.'	",
source : "4.19"},
{highlight : "Where they're seated in a restaurant, and how they're treated by the staff, are an important part of their first impression of a restaurant.	",
quote : "",
source : "9.16"},
{highlight : "The manager told them to order dessert on the house, 'it was really cool'.	",
quote : "When the manager asked how everything was, they told him they were 'normally happy with the food, but still hungry' since the portions were smaller. The manager told them to order dessert, on the house and gave them 2 drink tickets. Even thought the dessert was tiny, since it was paid for 'it was really cool.'	",
source : "5.24"},
{highlight : "It became a tradition because they started to remember their family.	",
quote : "They found the Italian restaurant intially through word of mouth and after going a couple times as a family, it became tradition because they started to remember their favorite meals and the servers came to know their family.	",
source : "7.1"},
{highlight : "The waitress knows me and tells me what's extra special on the menu.	",
quote : "At the restaurant where they're a regular: 'the waitress knows me. We catch up. She tells me what's new on the menu, what's extra special, what they're getting in for the season.'	",
source : "9.31"},
{highlight : "I sat in the last seat and felt a little isolated.	",
quote : "The most recent not-great restaurant experience they had was not great because 'I sat in the last seat and felt a little isolated' and 'the service was aggressive - not friendly.'	",
source : "9.24"},
{highlight : "They like OpenTable because it's not crowded with chain restaurants.	",
quote : "They like OpenTable because of the 'variety...not crowded with chain restaurants.' They like the history, the point system that adds up to gift certificates that are 'fairly easy to use.' It's not the only way to do research or make reservations 'but for me, it's the go-to app.'	",
source : "11.38"},
{highlight : "Addition to bad service the bill was incorrect and the manager had to be involved.	",
quote : "Recently they had a bad experience despite good food because in addition to bad service the bill was incorrect and the manager had to be involved.	",
source : "4.6"},
{highlight : "While they normally 'don't respond to email,' they 'love' getting discounts.	",
quote : "While they normally 'don't respond to email,' they 'love' getting discounts and offers so they do appreciate emails from restaurants that offer those.	",
source : "1.17"},
{highlight : "I would have preferred if they would have not charged as much as they did.	",
quote : "They were 'kind of hotter than normal' and 'fed up' despite the manager being really nice and fixing the wrong charge because 'I would have preferred if they would have not charged as much as they did. Maybe just charge us for the other things we ordered? I believe that is a good way that makes people coming back to your restaurant.'	",
source : "4.17"},
]

function randomQuote() {
  let random = quotes[Math.floor(Math.random() * quotes.length)];
  quotation.innerText = `${random.quote}`;
  source.innerText = random.source;
  highlight.innerText = random.highlight;
}

randomQuote();

document.querySelector("button").addEventListener('click', randomQuote)